_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 0e9afc70-815f-4980-8c13-7e9129dee9d5
name: FeTest
mail: sourojeet.paul@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /match-details
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
